micronaut.application.name = 'vannevar'
flyway.datasources.default.enabled = true
netty.default.allocator.max-order = 3

[datasources.default]
url = 'jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
username = 'sa'
password = ''
driver-class-name = 'org.h2.Driver'
dialect = 'H2'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'
